default: &default
  adapter: postgresql
  host: <%= Rails.application.credentials.db[:db_host] %>
  port: <%= Rails.application.credentials.db[:db_port] %>
  username: <%= Rails.application.credentials.db[:db_username] %>
  password: <%= Rails.application.credentials.db[:db_password] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kursverteiler-development

test:
  <<: *default
  database: kursverteiler-test

production:
  <<: *default
  database: kursverteiler
