default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') {} || Rails.application.credentials.db[:db_host] %>
  port: <%= ENV.fetch('DB_PORT') {} || Rails.application.credentials.db[:db_port] %>
  username: <%= ENV.fetch('DB_USERNAME') {} || Rails.application.credentials.db[:db_username] %>
  password: <%= ENV.fetch('DB_PASSWORD') {} || Rails.application.credentials.db[:db_password] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kursverteiler-development

test:
  <<: *default
  database: kursverteiler-test

staging:
  <<: *default
  database: kursverteiler-staging

production:
  <<: *default
  database: kursverteiler
