name: Brakeman

on: [push]

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup Brakeman
      env:
        BRAKEMAN_VERSION: '5.0.4'
      run: |
        gem install brakeman --version $BRAKEMAN_VERSION
    - name: Scan
      continue-on-error: true
      run: |
        brakeman -f sarif -o results.sarif .
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
