name: Brakeman

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'feature/**'
      - 'release/**'

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup Brakeman
      env:
        BRAKEMAN_VERSION: '5.4.1'
      run: |
        gem install brakeman --version $BRAKEMAN_VERSION
    - name: Scan
      continue-on-error: false
      run: |
        brakeman -f sarif -o results.sarif .
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
